import json
import random
import string
import csv

students_raw = {
"9th Grade": [
"ALFARO AISPURO CÉSAR GABRIEL", "AMEZQUITA GUERRA EMILIANO", "ÁNGULO OCHOA JOSÉ CARLOS", "BÁEZ ROBLES JAVIER SANTIAGO", "BARRAZA URTUSUASTEGUI RODRIGO", "CAMACHO LEYVA JUAN CARLOS", "CASTRO ESPARRAGOZA JUAN DANIEL", "CASTRO GUTIÉREZ ROBERTO", "FING RAMÍREZ EMILIANO", "FLORES PÉREZ JOSE BENITO", "GALLEGOS IBARRA EMMANUEL", "GAMBOA MATA HUGO ARTURO", "LEAL QUINTANA JESÚS DANIEL", "LEYVA PEÑA CRISTIAN EZAHÚ", "LOMELÍ CORTÉS EMILIO", "LUNA MEDINA JOSÉ FERNANDO", "MEDINA QUINTERO SEBASTIÁN", "NAVARRETE ARAGON LUKA", "RÁMOS HACH SERGIO", "ROCHÍN CASTRO RICARDO", "ROCHÍN RUIZ GERARDO", "RUELAS MEDINA SEBASTIAN", "VALENZUELA PÉREZ JESUS MARIO", "VEJAR ESCAMILLA MARTIN"
],
"10th Grade": [
"ALVARADO TREVIÑO EDUARDO", "BAÑUELOS SANTANA SANTIAGO NATANAEL", "BARRÓN SANTOS DEREK IVÁN", "BLANCO NIEBLA JESÚS MANUEL", "BELTRÁN MORGAN DIEGO JACIM", "CONTRERAS CANO PAULO", "FITZGERALD MARTÍNEZ MAXIMILIANO", "GONZÁLEZ CARDENAS OSCAR EDUARDO", "GUERRERO CHÁVEZ RODOLFO", "HERNÁNDEZ BELTRÁN MARCO ANTONIO", "HERNÁNDEZ MENDOZA LUIS ÁNGEL", "IBARRA GONZÁLEZ MAXIMILIANO", "LAGARDA ESCOBOSA SANTIAGO", "LOMELÍ CORTÉS IGNACIO", "LÓPEZ VILLASEÑOR JOSÉ ROBERTO", "MALO BAZUA BENJAMIN", "MEDINA MANJARREZ SANTIAGO", "PÉREZ ZAZUETA GABRIEL ALFONSO", "POMPA ONTIVEROS CARLOS", "RAMOS AGUILAR LUCAS ANTONIO", "ROBLES RUBIO MIGUEL ANGEL", "SAN MARTIN ESPINOZA IKER ANTONIO", "SANCHEZ OTAÑEZ EMILIANO RAFAEL", "SOLÍS CORDOVA ÁNGEL YAHEL", "VIDAÑA CARRILLO GILBERTO", "ZAZUETA VILLAREAL SANTIAGO"
],
"11th Grade": [
"AMEZQUITA GUERRA DIEGO", "BARRANTES OSUNA LUIS ARTURO", "BERNAL AVALOS SANTIAGO RAFAEL", "BLANCO TOLOSA ALEJANDRO", "BOLÍVAR FÉLIX THEOJARYS SEBASTIAN", "CASTRO VALDEZ CARLOS MARIO", "GARCÍA RÍOS JOHANN EMILIO", "GUERRERO ESPINOZA TOBIAS", "HERMOSILLO BERRELLEZA PAULO", "LIZÁRRAGA CASTAÑEDA JOSE MARTIN", "LÓPEZ BERNAL DIEGO ENRIQUE", "LÓPEZ JIMENEZ RICARDO", "MANRIQUE AGUILAR LUIS EMILIO", "MELENDREZ OLIVARRÍA VICTOR ALEXIS", "MEZA PEREZ DIEGO", "MORA SOTO JESÚS EDUARDO", "MURGUÍA RUÍZ MÁXIMO", "NAVARRETE ARAGÓN MIKEL", "PRIETO FLORES GUILLERMO", "RENDÓN GUERRERO JOSÉ ÁNGEL", "RIVERA TORRES DIEGO ISAAC", "ROBLES ANGULO CONSTANTINO", "SALAZAR BOJORQUEZ SANTIAGO", "SALAZAR TAMAYO SANTIAGO", "VALENZUELA AGUILASOCHO SALVADOR", "VALENZUELA DOMÍNGUEZ IAN ALEJANDRO", "VIEDAS RIVAS ISSAC", "WONG MERCADO ALBERTO YIHUN"
],
"12th Grade": [
"AGUERREBERE LEÓN ERICK DAVID", "AMEZQUITA GUERRA RIGOBERTO", "ARCE PALAZUELOS KEVIN", "BAEZ ROBLES CARLOS EMILIO", "CAZARES MORALES JOSE ROGELIO", "DOMÍNGUEZ PEREZ RICARDO", "ESCOBOSA GÜEMEZ JESÚS FRANCISCO", "FERNÁNDEZ TABOADA NICOLAS", "GALLEGOS ÁLVAREZ RODRIGO", "GAMBOA MATA GUILLERMO ENRIQUE", "GARCÍA MEDINA ALAN", "GASTÉLUM CASTRO GERARDO", "GÓMEZ DOMÍNGUEZ KARLOS ALBERTO", "GORDILLO ESPARRAGOZA EMILIO", "GUTIÉRREZ SUÁREZ SEBASTIAN", "HAYASHI MORA JOSÉ HUMBERTO", "HERMIDA SÁNCHEZ JONATHAN ALFONSO", "HERNANDEZ BORBOA JESÚS ENRIQUE", "LEAL QUINTANA JUAN ANTONIO", "LIZÁRRAGA GALLEGOS JULIO CÉSAR", "LIZÁRRAGA ROCHA NOLBERTO", "NAVARRETE ARAGON ANGEL DANIEL", "QUEZADA LIZÁRRAGA MARCO CÉSAR", "RAMOS BERNAL JESÚS HECTOR", "RAMOS SILVA MAX ARTURO", "RENTERÍA BELTRÁN JOSÉ FERNANDO", "SANTANA BON NICOLÁS", "TAN ZHANG FELIPE", "VALENZUELA ARTEAGA JAVIER", "VIZCARRA JIMÉNEZ MARCO ANTONIO"
]
}

def generate_code(length=5):
    return ''.join(random.choices(string.ascii_uppercase + string.digits, k=length))

students = []
used_codes = set()

for grade, names in students_raw.items():
    for name in names:
        code = generate_code()
        while code in used_codes:
            code = generate_code()
        used_codes.add(code)
        
        students.append({
            "accessCode": code,
            "name": name,
            "grade": grade,
            "group": "A" # Default group since none is provided in the image
        })

with open(r"c:\Users\PC01\Documents\StudentDay\students.json", "w", encoding="utf-8") as f:
    json.dump(students, f, indent=2, ensure_ascii=False)

with open(r"c:\Users\PC01\Documents\StudentDay\students.csv", "w", encoding="utf-8", newline="") as f:
    writer = csv.DictWriter(f, fieldnames=["accessCode", "name", "grade", "group"])
    writer.writeheader()
    writer.writerows(students)

print(f"Generated {len(students)} student codes successfully.")
